config/routes.rb
Task::Application.routes.draw do

  devise_for :users

  resources :todos

  resources :tasklists

  get "landing_pages/home"

 root :to => 'landing_pages#home'
  

end

app/models/tasklist.rb
class Tasklist < ActiveRecord::Base
  belongs_to :user

  has_many :todos, :dependent => :destroy
  attr_accessible :title, :user_id
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :Tasklist
  attr_accessible :completed, :description, :priority, :title, :Tasklist_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :name, :password, :password_confirmation, :remember_me
  
  has_many :tasklists, :dependent => :destroy
  
  validates :name, presence: true
  validates :password, length: {minimum: 6}
  emailFormatValidation = /[a-z.-]+@[a-z \d .-]+.[a-z]+/i
  validates :email, format: {with: emailFormatValidation}, uniqueness: true
  validates :password, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(user)
        return landing_pages_home_url
	end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def home
  	if !user_signed_in?
  		redirect_to  new_user_session_path
  		
  	end
  end
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  def index
    if user_signed_in?
  	 @task_lists = Tasklist.where(user_id: current_user)
    else
      @task_lists = Tasklist.all
    end
  end

  def new
  	@task_list = Tasklist.new
  end

  def create
  	@task_list = Tasklist.new(params[:tasklist])
  	if(@task_list.user_id != current_user.id)
      redirect_to root_path
    else
      if @task_list.save
        Notifications.new_tasklist(@task_list).deliver
    		redirect_to tasklists_path
    	else
    		render 'new'
    	end
    end
  end

  def show
    @task_list = Tasklist.find(params[:id])
  end

  def edit
    @task_list = Tasklist.find(params[:id])
  end

  def update
    @task_list = Tasklist.find(params[:id])
    if @task_list.update_attributes(params[:tasklist])
      redirect_to tasklist_path(@task_list.id)
    else
      render 'edit'
    end
  end

  #delete a user
  def destroy
    @task_list = Tasklist.find(params[:id])
    @task_list.destroy
    redirect_to tasklists_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    if user_signed_in?
      @todos = Todo.all
    else 
      @todos = []
    end
  end

  def show
      @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def create
    @todo = Todo.new(params[:todo])
    if @todo.save
      redirect_to todos_path  
    else
      render 'new'
    end

  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update_attributes(params[:todo])
      redirect_to todo_path(@todo.id)
    else
      render 'edit'
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #index - shows all Users
  def index
    @users = User.all
  end

  #new and create - create a new user
  # def new
  # 	@user = User.new
  # end

  # def create
  # 	@user = User.new(params[:user])
  # 	if @user.save
  # 		redirect_to users_path
  # 	else
  #     render 'new'
  # 	end
  # end



  #show - shows a specific user based on the user_id
  def show
    @user = User.find(params[:id])
  end

  #edit and update - edit a user that was created previously
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  #delete a user
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task</title>
  <link rel="stylesheet" type="text/css" ref="../assets/bootstrap.min.css">
  <script src="../assets/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default " role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Tasks</a>
  </div>

    

    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Lists <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "new list", new_tasklist_path %></li>
          <li><%= link_to "lists", tasklists_path %></li>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tasks <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "new task", new_todo_path %></li>
          <li><%= link_to "tasks", todos_path %></li>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
      <li>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
      </li>
      <% else %>
      <li>
        <%= link_to('Login', new_user_session_path)  %>  
      </li>
    <% end %>
  </ul>
</nav>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

<script>
  $('.dropdown-toggle').dropdown();
</script>

</body>
</html>

app/views/notifications/new_tasklist.text.erb
<%= @greeting %>, you just created a new task list!Check it out, and maybe add some tasks to it<%= tasklist_url(@id)%>

app/views/tasklists/edit.html.erb
<div class="error-msg">
  <% if @task_list.errors.any? %>
      <ul>
      <% @utask_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <%end%>
</div>

<%= form_for(@task_list) do |f| %>
	<div class="field">
    	<p>title</p> 
    	<%= f.text_field :title%>
    </div>
    <div class="field">
    	<p>user</p> 
     	<%= f.collection_select :user_id, User.all, :id, :name%>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/tasklists/index.html.erb
<table>
	<tr>
		<td >title</td>
		<td >user</td>
	</tr>
<% @task_lists.each do |task_list| %>
	<tr>

		<td><%= task_list.title %></td>
		<td><%= task_list.user.name %></td>
		<td><%= link_to "show list", tasklist_path(task_list.id) %> </td>
		<td><%= link_to "edit list", edit_tasklist_path(task_list.id) %> </td>
		<td><%= link_to "destroy list", task_list, confirm: "you sure you want to do this?", method: :delete %> </td>
	</tr>
<% end %>
</table>

app/views/tasklists/new.html.erb
<div class="error-msg">
  <% if @task_list.errors.any? %>
      <ul>
      <% @utask_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <%end%>
</div>

<%= form_for(@task_list) do |f| %>
	<div class="field">
    	<p>title</p> 
    	<%= f.text_field :title%>
    </div>
    <div class="field">
     	<%= f.hidden_field :user_id, :value =>current_user.id%>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/tasklists/show.html.erb
<%= @task_list.title %>
<%= @task_list.user.name %>

app/views/todos/edit.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.select(:priority, options_for_select([['high', 'high'], ['medium', 'medium'], ['low', 'low']], 3)) %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :Tasklist %><br />
    <%= f.collection_select :Tasklist_id, Tasklist.all, :id, :title%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Priority</th>
    <th>Description</th>
    <th>Completed</th>
    <th>Tasklist</th>
  </tr>

<% @todos.each do |todo| %>
  <tr>
    <td><%= todo.title %></td>
    <td><%= todo.priority %></td>
    <td><%= todo.description %></td>
    <td><%= todo.completed %></td>
    <td><%= todo.Tasklist.title %></td>
    <td><%= link_to 'Show', todo %></td>
    <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/todos/new.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.select(:priority, options_for_select([['high', 'high'], ['medium', 'medium'], ['low', 'low']], 3)) %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :Tasklist %><br />
    <%= f.collection_select :Tasklist_id, Tasklist.all, :id, :title%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/show.html.erb
<p>
  <b>Title:</b>
  <%= @todo.title %>
</p>

<p>
  <b>Priority:</b>
  <%= @todo.priority %>
</p>

<p>
  <b>Description:</b>
  <%= @todo.description %>
</p>

<p>
  <b>Completed:</b>
  <%= @todo.completed %>
</p>

<p>
  <b>Tasklist:</b>
  <%= @todo.Tasklist.title %>
</p>

app/views/users/edit.html.erb
<div class="error-msg">
  <% if @user.errors.any? %>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <%end%>
</div>

<%= form_for(@user) do |f| %>
	<div class="field">
    	<p>name</p> 
    	<%= f.text_field :name%>
    </div>
    <div class="field">
    	<p>email</p> 
     	<%= f.text_field :email%>
    </div>
    <div class="field">
    	<p>password</p> 
     	<%= f.text_field :password%>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/index.html.erb
<table>
	<tr>
		<td >name</td>
		<td >email</td>
		<td >password</td>
	</tr>
<% @users.each do |user| %>
	<tr>

		<td><%= user.name %></td>
		<td><%= user.email %></td>
		<td><%= user.password %></td>

		<td><%= link_to "show user", user_path(user.id) %> </td>
		<td><%= link_to "edit user", edit_user_path(user.id) %> </td>
		<td><%= link_to "destroy user", user, confirm: "you sure you want to do this?", method: :delete %> </td>
	</tr>
<% end %>
</table>

app/views/users/new.html.erb
<div class="error-msg">
  <% if @user.errors.any? %>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <%end%>
</div>

<%= form_for(@user) do |f| %>
	<div class="field">
    	<p>name</p> 
    	<%= f.text_field :name%>
    </div>
    <div class="field">
    	<p>email</p> 
     	<%= f.text_field :email%>
    </div>
    <div class="field">
    	<p>password</p> 
     	<%= f.text_field :password%>
    </div>
    <div class="field">
      <p>password confirmation</p> 
      <%= f.text_field :password_confirmation%>
    </div>
  
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<p><%= @user.email %></p>
<p><%= @user.password %></p>